gigs/models.py
class User:

    def __init__(self, email, display, first, last, city, state, country, bio):
        self.email = email
        self.display = display
        self.first = first
        self.last = last
        self.location = {'city': city, 'state': state, 'country': country}
        self.bio = bio

    @property
    def fullname(self):
        return '{} {}'.format(self.first, self.last)

    def __repr__(self):
        return "User('{}', '{}', '{}', '{}', '{}', '{}')".format(self.email, self.display, self.first, self.last, self.location, self.bio)

class Gig:

    def __init__(self, user_id, date, time, venue, event, city, state, country):
        self.user_id = user_id
        self.date = date
        self.time = time
        self.venue = venue
        self.event = event
        self.location = {'city': city, 'state': state, 'country': country}
           
    def __repr__(self):
        return "Gig('{}', '{}', '{}', '{}', '{}', '{}')".format(self.user_id, self.date, self.time, self.venue, self.event, self.location)

gigs/__init__.py
from flask import Flask

from .models import User, Gig
from .routes.auth import auth
from .routes.main import main

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    app.register_blueprint(main)
    app.register_blueprint(auth)

    return app

gigs/routes/auth.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from gigs.helpers import apology, get_countries, get_states
from gigs.extensions import conn, db
from gigs.models import Gig, User

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=["GET", "POST"])
def register():
    if request.method == "POST":
        
        form = request.form.get
        email = form("email")
        password = form("password")
        confirmation = form("password-confirmation")
   
        if not email:
            return apology("must provide email")
        elif not password:
            return apology("must provide password")
        elif not confirmation or confirmation != password:
            return apology("Password's confirmation does not match")

        hash = generate_password_hash(password)
        user = User(form("email"), form('display-name'), form('first-name'), form('last-name'), form('city'), form('state'), form('country'), form('bio'))

        try:
            db.execute("""INSERT INTO users(email, hash, display, first, last, city, state, country, bio) VALUES ('{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}')"""
            .format(user.email, hash, user.display, user.first, user.last, user.location['city'], user.location['state'], user.location['country'], user.bio))
        except Exception as e:
            print(e) 
            return apology("user already exists")
        finally:
            conn.commit()

        db.execute("SELECT * FROM users WHERE email = '{}'".format(user.email))        
        row = db.fetchone() 

        session["user_id"] = row[0]
        return redirect('/')    

    return render_template('register.html')

@auth.route('/login', methods=["GET", "POST"])
def login():
    session.clear()

    if request.method == "POST":

        if not request.form.get("email"):
            return apology("must provide username", 403)

        elif not request.form.get("password"):
            return apology("must provide password", 403)

        db.execute("SELECT * FROM users WHERE email = '{}'".format(request.form.get("email")))
        rows = db.fetchall()
        if len(rows) != 1 or not check_password_hash(rows[0][2], request.form.get("password")):
            return apology("invalid username and/or password", 403)           

        session["user_id"] = rows[0][0]
        return redirect("/profile")

    return render_template('login.html')    

@auth.route('/change_login', methods=["POST"])
def change_login():
    email = request.form.get('email')
    password = request.form.get('password')
    
    if not password and not email:
        return apology("all fields are required", 400)

    if password:
        hash = generate_password_hash(password)
        try:
            db.execute("UPDATE users SET hash = '{}' WHERE id = '{}'".format(hash, session["user_id"]))
        except: 
            return apology("problem updating password")
    if email:
        try:
            db.execute("UPDATE users SET email = '{}' WHERE id = '{}'".format(email, session["user_id"]))
        except: 
            return apology("problem updating email")

    conn.commit()    
    return render_template('account.html', message="Login information updated successfully!")

@auth.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

gigs/routes/main.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from gigs.helpers import login_required, apology, get_countries, get_states
from gigs.extensions import conn, db
from gigs.models import Gig, User

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/account', methods=["GET", "POST"])
@login_required
def account():
    db.execute("SELECT * FROM users WHERE id = '{}'".format(session["user_id"]))
    row = db.fetchone()

    return render_template('account.html', message=False, display=row[3])

@main.route('/add', methods=["GET", "POST"])
@login_required
def add():
    if request.method == "POST":
        form = request.form.get

        if not form('date'):
            return apology("must specify date")
        elif not form('venue'):
            return apology("must specify venue name")
        elif not form('city'):
            return apology("must specify city")
        elif not form('country'):
            return apology("must specify country")
        
        gig = Gig(session["user_id"], form('date'), form('time'), form('venue'), form('event'), form('city'), form('state'), form('country'))
        
        try:
            db.execute("""INSERT INTO gigs(user_id, date, venue, event, city, state, country, time) VALUES ('{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}')""".format(gig.user_id, gig.date, gig.venue, gig.event, gig.location['city'], gig.location['state'], gig.location['country'], gig.time))
        except Exception as error:
            print(error) 
            return apology("Invalid request")
        finally:
            conn.commit()
                
        return redirect(url_for('main.profile'))
        
      
    return render_template('add.html', countries=get_countries(), states=get_states())

    
@main.route('/profile', methods=["GET", "DELETE"])
@login_required
def profile():
    db.execute("SELECT * FROM users WHERE id = '{}'".format(session["user_id"]))
    row = db.fetchone()
    
    db.execute("SELECT *, to_char(time, 'HH24:MI') as time FROM gigs WHERE user_id = '{}' ORDER BY date ASC".format(session["user_id"]))
    gigs = db.fetchall()

    display = row[3]
    name = '{} {}'.format(row[4], row[5])
    state = row[7]
    bio = row[10]
    if len(state) is 0:
        location = '{}, {}'.format(row[6], row[8])
    else:
        location = '{}, {}, {}'.format(row[6], row[7], row[8])
    
    return render_template('profile.html', display=display, name=name, location=location, gigs=gigs, bio=bio)
 
@main.route('/remove/<id>', methods=["POST"])
def remove(id):
    try:
        db.execute("DELETE FROM gigs WHERE id = '{}'".format(id))
    except: 
        return apology("can't delete")
    finally:
        conn.commit()
    
    return redirect(url_for('main.profile'))

@main.route('/delete_account', methods=["POST"])
def delete_account():
    try:
        db.execute("DELETE FROM users WHERE id = '{}'".format(session["user_id"]))
    except: 
        return apology("can't delete")
    finally:
        conn.commit()
    
    return redirect(url_for('auth.logout'))


@main.route('/change_bio', methods=["POST"])
def bio():
    bio = request.form.get('bio')

    if bio:
        try:
            db.execute("UPDATE users SET bio = '{}' WHERE id = '{}'".format(bio, session["user_id"]))
        except:
            return apology("problem updating bio")

    return redirect(url_for('main.profile'))

gigs/templates/Login.html
{% extends "layout.html" %}

<!-- Page Title -->
{% block title %} Log In {% endblock %}

<!-- Main -->
{% block main %}
<h3>Login</h3>
<br>
<form action="/login" method="POST" class="needs-validation" novalidate>
    <!-- Login Information -->
    <div class="form-row">
        <!-- Email -->
        <div class="col-md-4 mb-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" placeholder="Email" required>
        </div>
    </div>
    <div class="form-row">
        <!-- Password -->
        <div class="col-md-4 mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" autocomplete="true" placeholder="Password" required>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Login</button>
    <br><br>
    <p>Don't have an account yet? <a href="register">Create one here!</a></p>
    {% endblock %}

gigs/templates/account.html
{% extends "layout.html" %}
{% block title %} Account {% endblock %}

{% block main %}
<div class="accordion" id="accordionExample">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Change Login Information
              </button>
            </h2>
          </div>
      
          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              {% if message %}
              <p><strong>{{message}}</strong></p>
              {% endif %}
              <form action="{{ url_for('auth.change_login') }}" method="POST">
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Email">
                        </div>
                    </div>    
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="password">Password</label>
                            <input type="password" autocomplete="off" class="form-control" name="password" placeholder="Password">
                        </div>
                    </div>
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingThree">
            <h2 class="mb-0">
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Delete Account
              </button>
            </h2>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
                <form action="{{ url_for('main.delete_account') }}" method="POST">
                    <h6>This will delete your account, there's no undo for that!</h6>
                    <br>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

gigs/templates/add.html
{% extends "layout.html" %} 
{% block title %} Add Gig {% endblock %} 
{% block main %}
<h3>New Gig</h3>
<br />
<form action="{{ url_for('main.add')}}" method="POST" class="needs-validation" novalidate>
	<div class="form-row">
		<div class="col-md-3">
			<label for="date">Date</label>
			<input
				type="date"
				name="date"
				class="form-control is valid"
				required
			/>
			<div class="invalid-feedback">you must specify date</div>
		</div>

		<div class="col-md-1.5">
			<label for="time">Time</label>
			<input
				type="time"
				name="time"
				class="form-control is valid"
				required
			/>
			<div class="invalid-feedback">you must specify date</div>
		</div>
		<div class="form-group col-md-3">
			<label for="venue">Venue</label>
			<input type="text" name="venue" placeholder="Venue" class="form-control" required />
			<div class="invalid-feedback">you must specify venue name</div>
		</div>

		<div class="form-group col-md-3 mb-2">
			<label for="event"
				>Event Name
				<span class="small"><span class="red">*</span>optional</span></label
			>
			<input type="text" name="event" placeholder="Event" class="form-control" />
		</div>
	</div>
	<div class="form-row">
		<div class="form-group col-md-2">
			<label for="city">City</label>
			<input type="text" name="city" placeholder="City" class="form-control" required />
			<div class="invalid-feedback">you must specify city</div>
		</div>
		<div class="form-group col-md-3">
			<label for="state"
				>State
				<span class="small"><span class="red">*</span>USA only</span></label
			>
			<select name="state" class="form-control">
				<option value="" selected>N/A</option>
				{% for state in states %}
				<option value="{{state}}">{{state}}</option>
				{% endfor %}
			</select>
		</div>
		<div class="form-group col-md-3">
			<label for="country">Country</label>
			<select name="country" class="form-control" required>
				<option value="" selected disabled>Choose</option>
				{% for country in countries %}
				<option value="{{country}}">{{country}}</option>
				{% endfor %}
			</select>
			<div class="invalid-feedback">you must specify a country</div>
		</div>
	</div>
	<button type="submit" class="btn btn-primary mb-2">Submit</button>
</form>

<script>
	// Example starter JavaScript for disabling form submissions if there are invalid fields
	;(function() {
		'use strict'
		window.addEventListener(
			'load',
			function() {
				// Fetch all the forms we want to apply custom Bootstrap validation styles to
				var forms = document.getElementsByClassName('needs-validation')
				// Loop over them and prevent submission
				var validation = Array.prototype.filter.call(forms, function(form) {
					form.addEventListener(
						'submit',
						function(event) {
							if (form.checkValidity() === false) {
								event.preventDefault()
								event.stopPropagation()
							}
							form.classList.add('was-validated')
						},
						false
					)
				})
			},
			false
		)
	})()
</script>
{% endblock %}

gigs/templates/apology.html
{% extends "layout.html" %}

{% block title %} Apology {% endblock %}

{% block main %}
    <img alt="{{ top }}" class="border" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png" title="{{ top }}"> 
{% endblock %}

gigs/templates/index.html
{% extends "layout.html" %}

{% block title %} Home {% endblock %}

{% block main %}
    <h3>Welcome to GIGS!</h3>
    <p>GIGS is a platform made for active performing musicians.</p>
    <h4>With GIGS you can:</h4>
    <ul>
        <li>Create your public account</li>
        <li>Organize your tour dates</li>
        <li>Share your content with other users</li>
    </ul>
{% endblock %}

gigs/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{{ url_for('static', filename='favicon.ico')}}" rel="icon">
    <script src="https://kit.fontawesome.com/e186010c30.js" crossorigin="anonymous"></script>
    <link href="{{ url_for('static', filename='styles.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css')}}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>GIGS - {% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light border">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="/static/logo.png" width="147" height="42" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto mt-2">
                {% if session.user_id %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.add') }}">Add Gig</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto mt-2">
                {% if session.user_id %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.account') }}">Account</a>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>     
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <br>
    <main class="container p-5">
        {% block main %}{% endblock %}
    </main>
    
    <script type=text/javascript src="{{url_for('static', filename='jquery.slim.min.js') }}"></script>
    <script src="{{url_for('static', filename='popper.min.js') }}"></script>
    <script src="{{url_for('static', filename='bootstrap.min.js') }}"></script>
</body>

</html>

gigs/templates/login.html
{% extends "layout.html" %}

{% block title %} Log In {% endblock %}

{% block main %}
<h3>Login</h3>
<br>
<form action="{{ url_for('auth.login') }}" method="POST" class="needs-validation" novalidate>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" placeholder="Email" required>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" autocomplete="true" placeholder="Password" required>
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Login</button>
    <br><br>
    <p>Don't have an account yet? <a href="{{ url_for('auth.register') }}">Create one here!</a></p>
{% endblock %}

gigs/templates/profile.html
{% extends "layout.html" %}
{% block title %} {{ display }} {% endblock %}

{% block main %}

<div class="media">
    <img src="/static/avatar.svg" class="mr-3" width="150" height="150" alt="Profile Picture">
    <div class="media-body">
        <h5 class="mt-0">{{ display }}</h5>
        <h6 class="mt-0">{{ name }}</h6>
        <h6 class="mt-0">{{ location }}</h6>
    </div>
</div>

<div class="media">
    <div class="media-body">
      <h3 class="badge badge-secondary">Biography <i class="far fa-edit" onclick="update()"></i></h3>
      
      {% if bio %}
      <p id="bio">{{ bio }}</p>
      {% else %}
      <p id="bio">&Tab; Bio goes here, whenever you're ready</p>
      {% endif %}
    </div>
</div>
<br>

<h3>Upcoming Gigs:</h3>
<br>
{% if gigs %}
<ul class="list-unstyled">
    {% for gig in gigs %}
    <li class="media">
        <time datetime={{gig[2]}} class="icon">
            <em class=day>Day</em>
            <strong class=month>Month</strong>
            <span class=day-num>#</span>
        </time>
        <div class="media-body">
            {% if gig[4] %}
            <h5 class="mt-0 mb-1">{{ gig[4] }}</h5>
            <h6 class="mt-0">{{ gig[3] }}</h6>
            {% else %}
            <h5 class="mt-0 mb-1">{{ gig[3] }}</h5>
            {% endif %}
            {% if gig[6] %}
            <h6 class="mt-0">{{ gig[5] }}, {{ gig[6]}}, {{ gig[7] }}</h6>
            {% else %}
            <h6 class="mt-0">{{ gig[5] }}, {{ gig[7] }}</h6>
            {% endif %}
            <h6 class="mt-0">{{ gig[11] }}</h6>
            <form action="/remove/{{gig[0]}}" method="POST">
                <button type="submit" class="btn btn-outline-danger">Remove</button>
            </form>
        </div>
    </li>
    {% endfor %}
{% else %}
    <h4>you have not added any gigs yet</h4>
{% endif %}
</ul>

<script src="{{ url_for('static', filename='moment.min.js')}}"></script>
<script src="{{ url_for('static', filename='dateFormat.js')}}"></script>
<script src="{{ url_for('static', filename='bio.js')}}"></script>

{% endblock %}

gigs/templates/register.html
{% extends "layout.html" %}
{% block title %} Register {% endblock %}

{% block main %}
<h3>Login Information</h3>
<br>
<form action="{{ url_for('auth.register') }}" method="POST">
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="email">Email</label>
            <input type="email" class="form-control required" name="email" placeholder="Email" required>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="password">Password</label>
            <input type="password" autocomplete="off" class="form-control required" name="password" placeholder="Password" required>
        </div>
        <div class="col-md-4 mb-3">
            <label for="password-confirmation">Password Confirmation</label>
            <input type="password" autocomplete="off" class="form-control required" name="password-confirmation" placeholder="Password Confirmation" required>
        </div>
    </div>
    <br>
    <h3>Profile Information</h3>
    <br>
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="display-name">Display Name</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                </div>
                <input type="text" autocomplete="off" class="form-control required"name="display-name" placeholder="Display Name" aria-describedby="inputGroupPrepend" required>
            </div>
        </div>
    </div>
    <div class="form-row ">

        <div class="col-md-4 mb-3 ">
            <label for="first ">First name</label>
            <input type="text" autocomplete="off" class="form-control required" name="first-name" placeholder="First name" required>
        </div>
        <div class="col-md-4 mb-3 ">
            <label for="last">Last name</label>
            <input type="text" autocomplete="off" class="form-control required" name="last-name" placeholder="Last name" required>
        </div>
    </div>
    <div class="form-row ">
        <div class="col-md-4 mb-3 ">
            <label for="city">City</label>
            <input type="text" autocomplete="off" class="form-control" name="city" placeholder="City">
        </div>
        <div class="col-md-2 mb-2 ">
            <label for="state">State</label>
            <input type="text" autocomplete="off" class="form-control" name="state" placeholder="State">
        </div>
        <div class="col-md-3 mb-3 ">
            <label for="country">Country</label>
            <input type="text" autocomplete="off" class="form-control" name="country" placeholder="Country">
        </div>
    </div>
    <div class="col-md-8 mb-2 ">
        <label for="bio">Short Bio</label>
        <textarea class="form-control" name="bio" placeholder="bio" rows="4" cols="100"></textarea>
    </div>
    <br>
    <div id="error"></div>
    <button class="btn btn-primary" id="submit" type="submit">Register</button>
</form>

<script src="{{ url_for('static', filename='register.js')}}"></script>

{% endblock %}